
stages:
  - detect
  - test
  - trigger

job:
  image: everpeace/curl-jq
  script:
    - 'export SOURCE=$(cat $TRIGGER_PAYLOAD | jq -r .object_attributes.source_branch)'
    - 'export PREVIOUS=$(cat $TRIGGER_PAYLOAD | jq -r .changes.title.previous)'
    - 'export CURRENT=$(cat $TRIGGER_PAYLOAD | jq -r .changes.title.current)'
    - 'if [ "$PREVIOUS" != "$CURRENT" ]; then curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=${SOURCE}" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"; fi'
    - echo $SOURCE
    - echo $PREVIOUS
    - echo $CURRENT
  only:
    - triggers


dast:
  script:
    - echo "DAST!"
  except:
    - triggers

