create table medicine
(
    id               bigint generated by default as identity
        constraint medicine_pkey
            primary key,
    description      varchar(255) not null,
    icon             varchar(255),
    manufacture_name varchar(255) not null,
    name             varchar(255) not null,
    constraint uk4jxl0awrpocq68gqtpnp8lajx
        unique (manufacture_name, name)
);

alter table medicine
    owner to jm;

create table role
(
    name varchar(25) not null
        constraint role_pkey
            primary key
);

alter table role
    owner to jm;

create table user_entities
(
    user_type varchar(31)  not null,
    id        bigint generated by default as identity
        constraint user_entities_pkey
            primary key,
    avatar    varchar(255),
    email     varchar(255) not null
        constraint uk_9qwti9qe1qo5kmm691yab7jkr
            unique,
    enabled   boolean,
    firstname varchar(255) not null,
    lastname  varchar(255) not null,
    password  varchar(255) not null
);

alter table user_entities
    owner to jm;

create table comment
(
    id        bigint generated by default as identity
        constraint comment_pkey
            primary key,
    content   varchar(255) not null,
    date_time timestamp    not null,
    user_id   bigint
        constraint fkeolektwax7gapggeent4eq4vg
            references user_entities
);

alter table comment
    owner to jm;

create table comment_reaction
(
    positive   boolean not null,
    client_id  bigint  not null
        constraint fkqoo8lkav28s0mr56n0rajn701
            references user_entities,
    comment_id bigint  not null
        constraint fkrkwlnq2025sav3ixnd4ue3nk0
            references comment,
    constraint comment_reaction_pkey
        primary key (client_id, comment_id)
);

alter table comment_reaction
    owner to jm;

create table doctor_review
(
    id         bigint generated by default as identity
        constraint doctor_review_pkey
            primary key,
    comment_id bigint
        constraint fkep99h2gpqn9q7ir4meuex81dr
            references comment,
    doctor_id  bigint
        constraint fkmkkaxpmgh9l35oradvw1p9po6
            references user_entities
);

alter table doctor_review
    owner to jm;

create table pet_entities
(
    pet_type    varchar(31)  not null,
    id          bigint generated by default as identity
        constraint pet_entities_pkey
            primary key,
    avatar      varchar(255),
    birth_day   date         not null,
    breed       varchar(255) not null,
    color       varchar(255),
    description varchar(255),
    gender      varchar(255) not null,
    name        varchar(255) not null,
    pet_size    varchar(255),
    weight      double precision,
    client_id   bigint
        constraint fkmyoxeof1icycalc9k74nx03g8
            references user_entities
);

alter table pet_entities
    owner to jm;

create table clinical_examination
(
    id          bigint generated by default as identity
        constraint clinical_examination_pkey
            primary key,
    date        date,
    is_can_move boolean,
    text        varchar(255),
    weight      double precision,
    doctor_id   bigint
        constraint fk2lktrsun7ar1y379pphm4m3be
            references user_entities,
    pet_id      bigint
        constraint fkcntayr86konn3jn9j54wronvc
            references pet_entities
);

alter table clinical_examination
    owner to jm;

create table diagnosis
(
    id          bigint generated by default as identity
        constraint diagnosis_pkey
            primary key,
    description varchar(255) not null,
    doctor_id   bigint
        constraint fkrk9onee1tssc7i8kot86x3ku0
            references user_entities,
    pet_id      bigint
        constraint fk71tm8nmjfu6pf1wga81xufyxq
            references pet_entities
);

alter table diagnosis
    owner to jm;

create table notification
(
    id          bigint generated by default as identity
        constraint notification_pkey
            primary key,
    description varchar(255),
    end_date    timestamp,
    event_id    varchar(255),
    location    varchar(255),
    start_date  timestamp,
    summary     varchar(255),
    pet_id      bigint
        constraint fkgd8gm06sd4sef2y8c5p4rgk8s
            references pet_entities
);

alter table notification
    owner to jm;

create table pet_contact
(
    id         bigint not null
        constraint pet_contact_pkey
            primary key
        constraint fk6pmpoop709qhv37w02r20wn8h
            references pet_entities,
    address    varchar(255),
    owner_name varchar(255),
    pet_code   varchar(255)
        constraint uk_n6ud0x01026f0m6q4s6y041j0
            unique,
    phone      bigint
);

alter table pet_contact
    owner to jm;

create table pet_found
(
    id        bigint generated by default as identity
        constraint pet_found_pkey
            primary key,
    latitude  varchar(255),
    longitude varchar(255),
    text      varchar(255),
    pet_id    bigint
        constraint fk9rl64mmwmhmw45kay2vv74dk7
            references pet_entities
);

alter table pet_found
    owner to jm;

create table procedure
(
    type                  varchar(31) not null,
    id                    bigint generated by default as identity
        constraint procedure_pkey
            primary key,
    date                  date,
    is_periodical         boolean,
    medicine_batch_number varchar(255),
    period_days           integer,
    medicine_id           bigint
        constraint fkk9t5hx9e3miol255bx16ltsa3
            references medicine,
    notification_id       bigint
        constraint fkjxe8eevk5wk94dd2diwlc5l2n
            references notification,
    pet_id                bigint
        constraint fklq33xglmi8iqw5f515ppbct1
            references pet_entities
);

alter table procedure
    owner to jm;

create table reproduction
(
    id           bigint generated by default as identity
        constraint reproduction_pkey
            primary key,
    child_count  integer,
    due_date     date,
    estrus_start date,
    mating       date,
    pet_id       bigint
        constraint fk53438nw838v8fwn377se22eqd
            references pet_entities
);

alter table reproduction
    owner to jm;

create table topic
(
    id               bigint generated by default as identity
        constraint topic_pkey
            primary key,
    content          varchar(255),
    creation_date    timestamp not null,
    is_closed        boolean,
    last_update_date timestamp not null,
    title            varchar(255),
    topic_starter_id bigint
        constraint fkdxanmf3r0ts46ynxo078unm9q
            references user_entities
);

alter table topic
    owner to jm;

create table topic_comments
(
    topic_id    bigint not null
        constraint fkia810jj3eu2p5ntkhvjp5y9t0
            references topic,
    comments_id bigint not null
        constraint uk_1vk0b7ydov59qm5w9jfmh8myd
            unique
        constraint fkai46ca03mwweu85iedk6djbin
            references comment
);

alter table topic_comments
    owner to jm;

create table treatment
(
    id           bigint generated by default as identity
        constraint treatment_pkey
            primary key,
    diagnosis_id bigint
        constraint fknjtteshx1j3nvbc9w09l68jdi
            references diagnosis
);

alter table treatment
    owner to jm;

create table treatment_procedure_list
(
    treatment_id      bigint not null
        constraint fkmre1lxgwaulk7gev3g82n9mq5
            references treatment,
    procedure_list_id bigint not null
        constraint uk_6shpj5bmdetscb50nfaxi86tn
            unique
        constraint fk3ytxy87bqxxgo2w0taa2a5blc
            references procedure
);

alter table treatment_procedure_list
    owner to jm;

create table user_role
(
    role_name varchar(25)
        constraint fkn6r4465stkbdy93a9p8cw7u24
            references role,
    user_id   bigint not null
        constraint user_role_pkey
            primary key
        constraint fkae2hlgni80dic3p64yftwm9te
            references user_entities
);

alter table user_role
    owner to jm;

create table verification_token
(
    id      bigint not null
        constraint verification_token_pkey
            primary key,
    user_id bigint not null
        constraint fk4dbx59fdx6hng18nmxa076ngv
            references user_entities
);

alter table verification_token
    owner to jm;

