drop table if exists appointment cascade;
drop table if exists clinical_examination cascade;
drop table if exists comment cascade;
drop table if exists comment_reaction cascade;
drop table if exists diagnosis cascade;
drop table if exists doctor_non_working cascade;
drop table if exists doctor_review cascade;
drop table if exists doctor_schedule cascade;
drop table if exists medicine cascade;
drop table if exists notification cascade;
drop table if exists pet_entities cascade;
drop table if exists pet_contact cascade;
drop table if exists pet_found cascade;
drop table if exists procedure cascade;
drop table if exists reproduction cascade;
drop table if exists role cascade;
drop table if exists topic cascade;
drop table if exists topic_comments cascade;
drop table if exists treatment cascade;
drop table if exists treatment_procedure_list cascade;
drop table if exists user_entities cascade;
drop table if exists user_role cascade;
drop table if exists verification_token cascade;

create table appointment
(
    id              int8 generated by default as identity,
    description     varchar(255) not null,
    start_date_time timestamp    not null,
    doctor_id       int8,
    pet_id          int8,
    primary key (id)
);

create table clinical_examination
(
    id          int8 generated by default as identity,
    date        date,
    is_can_move boolean,
    text        varchar(255),
    weight      float8,
    doctor_id   int8,
    pet_id      int8,
    primary key (id)
);

create table comment
(
    id        int8 generated by default as identity,
    content   varchar(255) not null,
    date_time timestamp    not null,
    user_id   int8,
    primary key (id)
);

create table comment_reaction
(
    positive   boolean not null,
    comment_id int8    not null,
    user_id    int8    not null,
    primary key (comment_id, user_id)
);

create table diagnosis
(
    id          int8 generated by default as identity,
    description varchar(255) not null,
    doctor_id   int8,
    pet_id      int8,
    primary key (id)
);

create table doctor_non_working
(
    id        int8 generated by default as identity,
    date      date,
    type      varchar(255),
    doctor_id int8,
    primary key (id)
);

create table doctor_review
(
    id         int8 generated by default as identity,
    comment_id int8,
    doctor_id  int8,
    primary key (id)
);

create table doctor_schedule
(
    id          int8 generated by default as identity,
    week_number int4,
    work_shift  varchar(255) not null,
    doctor_id   int8,
    primary key (id)
);

create table medicine
(
    id               int8 generated by default as identity,
    description      varchar(255) not null,
    icon             varchar(255),
    manufacture_name varchar(255) not null,
    name             varchar(255) not null,
    primary key (id)
);

create table notification
(
    id          int8 generated by default as identity,
    description varchar(255),
    end_date    timestamp,
    event_id    varchar(255),
    location    varchar(255),
    start_date  timestamp,
    summary     varchar(255),
    pet_id      int8,
    primary key (id)
);

create table pet_entities
(
    pet_type    varchar(31)  not null,
    id          int8 generated by default as identity,
    avatar      varchar(255),
    birth_day   date         not null,
    breed       varchar(255) not null,
    color       varchar(255),
    description varchar(255),
    gender      varchar(255) not null,
    name        varchar(255) not null,
    pet_size    varchar(255),
    weight      float8,
    client_id   int8,
    primary key (id)
);

create table pet_contact
(
    id         int8 not null,
    address    varchar(255),
    owner_name varchar(255),
    pet_code   varchar(255),
    phone      int8,
    primary key (id)
);

create table pet_found
(
    id        int8 generated by default as identity,
    latitude  varchar(255),
    longitude varchar(255),
    text      varchar(255),
    pet_id    int8,
    primary key (id)
);

create table procedure
(
    type                  varchar(31) not null,
    id                    int8 generated by default as identity,
    date                  date,
    is_periodical         boolean,
    medicine_batch_number varchar(255),
    period_days           int4,
    medicine_id           int8,
    notification_id       int8,
    pet_id                int8,
    primary key (id)
);
create table reproduction
(
    id           int8 generated by default as identity,
    child_count  int4,
    due_date     date,
    estrus_start date,
    mating       date,
    pet_id       int8,
    primary key (id)
);

create table role
(
    name varchar(25) not null,
    primary key (name)
);

create table topic
(
    id               int8 generated by default as identity,
    content          varchar(255),
    creation_date    timestamp not null,
    is_closed        boolean,
    last_update_date timestamp not null,
    title            varchar(255),
    topic_starter_id int8,
    primary key (id)
);

create table topic_comments
(
    topic_id    int8 not null,
    comments_id int8 not null
);

create table treatment
(
    id           int8 generated by default as identity,
    diagnosis_id int8,
    primary key (id)
);

create table treatment_procedure_list
(
    treatment_id      int8 not null,
    procedure_list_id int8 not null
);

create table user_entities
(
    user_type varchar(31)  not null,
    id        int8 generated by default as identity,
    avatar    varchar(255),
    email     varchar(255) not null,
    enabled   boolean,
    firstname varchar(255) not null,
    lastname  varchar(255) not null,
    password  varchar(255) not null,
    primary key (id)
);

create table user_role
(
    role_name varchar(25),
    user_id   int8 not null,
    primary key (user_id)
);

create table verification_token
(
    id      int8 not null,
    user_id int8 not null,
    primary key (id)
);

alter table if exists appointment drop constraint if exists FK5dp6w4epk82cl311bks0qna50;
alter table if exists appointment drop constraint if exists FKnpn9ly9v9v0iqiega7h4g54em;
alter table if exists clinical_examination drop constraint if exists FK2lktrsun7ar1y379pphm4m3be;
alter table if exists clinical_examination drop constraint if exists FKcntayr86konn3jn9j54wronvc;
alter table if exists comment drop constraint if exists FKeolektwax7gapggeent4eq4vg;
alter table if exists comment_reaction drop constraint if exists FKrkwlnq2025sav3ixnd4ue3nk0;
alter table if exists comment_reaction drop constraint if exists FKxas2egfepb5plys55xfip152;
alter table if exists diagnosis drop constraint if exists FKrk9onee1tssc7i8kot86x3ku0;
alter table if exists diagnosis drop constraint if exists FK71tm8nmjfu6pf1wga81xufyxq;
alter table if exists doctor_non_working drop constraint if exists FKd15qgnd64qqsrla3uollokfle;
alter table if exists doctor_review drop constraint if exists FKep99h2gpqn9q7ir4meuex81dr;
alter table if exists doctor_review drop constraint if exists FKmkkaxpmgh9l35oradvw1p9po6;
alter table if exists doctor_schedule drop constraint if exists FK558md60kc645xumv2wwxbwq6p;
alter table if exists notification drop constraint if exists FKgd8gm06sd4sef2y8c5p4rgk8s;
alter table if exists pet_entities drop constraint if exists FKmyoxeof1icycalc9k74nx03g8;
alter table if exists pet_contact drop constraint if exists FK6pmpoop709qhv37w02r20wn8h;
alter table if exists pet_found drop constraint if exists FK9rl64mmwmhmw45kay2vv74dk7;
alter table if exists procedure drop constraint if exists FKk9t5hx9e3miol255bx16ltsa3;
alter table if exists procedure drop constraint if exists FKjxe8eevk5wk94dd2diwlc5l2n;
alter table if exists procedure drop constraint if exists FKlq33xglmi8iqw5f515ppbct1;
alter table if exists reproduction drop constraint if exists FK53438nw838v8fwn377se22eqd;
alter table if exists topic drop constraint if exists FKdxanmf3r0ts46ynxo078unm9q;
alter table if exists topic_comments drop constraint if exists FKai46ca03mwweu85iedk6djbin;
alter table if exists topic_comments drop constraint if exists FKia810jj3eu2p5ntkhvjp5y9t0;
alter table if exists treatment drop constraint if exists FKnjtteshx1j3nvbc9w09l68jdi;
alter table if exists treatment_procedure_list drop constraint if exists FK3ytxy87bqxxgo2w0taa2a5blc;
alter table if exists treatment_procedure_list drop constraint if exists FKmre1lxgwaulk7gev3g82n9mq5;
alter table if exists user_role drop constraint if exists FKn6r4465stkbdy93a9p8cw7u24;
alter table if exists user_role drop constraint if exists FKae2hlgni80dic3p64yftwm9te;
alter table if exists verification_token drop constraint if exists FK4dbx59fdx6hng18nmxa076ngv;

alter table if exists medicine add constraint UK4jxl0awrpocq68gqtpnp8lajx unique (manufacture_name, name);
alter table if exists pet_contact add constraint UK_n6ud0x01026f0m6q4s6y041j0 unique (pet_code);
alter table if exists topic_comments add constraint UK_1vk0b7ydov59qm5w9jfmh8myd unique (comments_id);
alter table if exists treatment_procedure_list add constraint UK_6shpj5bmdetscb50nfaxi86tn unique (procedure_list_id);
alter table if exists user_entities add constraint UK_9qwti9qe1qo5kmm691yab7jkr unique (email);
alter table if exists verification_token add constraint UK_q6jibbenp7o9v6tq178xg88hg unique (user_id);
alter table if exists appointment add constraint FK5dp6w4epk82cl311bks0qna50
    foreign key (doctor_id) references user_entities;
alter table if exists appointment add constraint FKnpn9ly9v9v0iqiega7h4g54em
    foreign key (pet_id) references pet_entities;
alter table if exists clinical_examination add constraint FK2lktrsun7ar1y379pphm4m3be
    foreign key (doctor_id) references user_entities;
alter table if exists clinical_examination add constraint FKcntayr86konn3jn9j54wronvc
    foreign key (pet_id) references pet_entities;
alter table if exists comment add constraint FKeolektwax7gapggeent4eq4vg
    foreign key (user_id) references user_entities on delete cascade;
alter table if exists comment_reaction add constraint FKrkwlnq2025sav3ixnd4ue3nk0
    foreign key (comment_id) references comment;
alter table if exists comment_reaction add constraint FKxas2egfepb5plys55xfip152
    foreign key (user_id) references user_entities;
alter table if exists diagnosis add constraint FKrk9onee1tssc7i8kot86x3ku0
    foreign key (doctor_id) references user_entities;
alter table if exists diagnosis add constraint FK71tm8nmjfu6pf1wga81xufyxq
    foreign key (pet_id) references pet_entities;
alter table if exists doctor_non_working add constraint FKd15qgnd64qqsrla3uollokfle
    foreign key (doctor_id) references user_entities;
alter table if exists doctor_review add constraint FKep99h2gpqn9q7ir4meuex81dr
    foreign key (comment_id) references comment;
alter table if exists doctor_review add constraint FKmkkaxpmgh9l35oradvw1p9po6
    foreign key (doctor_id) references user_entities;
alter table if exists doctor_schedule add constraint FK558md60kc645xumv2wwxbwq6p
    foreign key (doctor_id) references user_entities;
alter table if exists notification add constraint FKgd8gm06sd4sef2y8c5p4rgk8s
    foreign key (pet_id) references pet_entities;
alter table if exists pet_entities add constraint FKmyoxeof1icycalc9k74nx03g8
    foreign key (client_id) references user_entities;
alter table if exists pet_contact add constraint FK6pmpoop709qhv37w02r20wn8h
    foreign key (id) references pet_entities;
alter table if exists pet_found add constraint FK9rl64mmwmhmw45kay2vv74dk7
    foreign key (pet_id) references pet_entities;
alter table if exists procedure add constraint FKk9t5hx9e3miol255bx16ltsa3
    foreign key (medicine_id) references medicine;
alter table if exists procedure add constraint FKjxe8eevk5wk94dd2diwlc5l2n
    foreign key (notification_id) references notification;
alter table if exists procedure add constraint FKlq33xglmi8iqw5f515ppbct1
    foreign key (pet_id) references pet_entities;
alter table if exists reproduction add constraint FK53438nw838v8fwn377se22eqd
    foreign key (pet_id) references pet_entities;
alter table if exists topic add constraint FKdxanmf3r0ts46ynxo078unm9q
    foreign key (topic_starter_id) references user_entities;
alter table if exists topic_comments add constraint FKai46ca03mwweu85iedk6djbin
    foreign key (comments_id) references comment;
alter table if exists topic_comments add constraint FKia810jj3eu2p5ntkhvjp5y9t0
    foreign key (topic_id) references topic;
alter table if exists treatment add constraint FKnjtteshx1j3nvbc9w09l68jdi
    foreign key (diagnosis_id) references diagnosis;
alter table if exists treatment_procedure_list add constraint FK3ytxy87bqxxgo2w0taa2a5blc
    foreign key (procedure_list_id) references procedure;
alter table if exists treatment_procedure_list add constraint FKmre1lxgwaulk7gev3g82n9mq5
    foreign key (treatment_id) references treatment;
alter table if exists user_role add constraint FKn6r4465stkbdy93a9p8cw7u24
    foreign key (role_name) references role;
alter table if exists user_role add constraint FKae2hlgni80dic3p64yftwm9te
    foreign key (user_id) references user_entities;
alter table if exists verification_token add constraint FK4dbx59fdx6hng18nmxa076ngv
    foreign key (user_id) references user_entities;

insert into role (name) values ('ADMIN');
insert into role (name) values ('MANAGER');
insert into role (name) values ('DOCTOR');
insert into role (name) values ('CLIENT');
insert into role(name) values ('UNVERIFIED_CLIENT');