alter table if not exists doctor_schedule
(
    id          int8 generated by default as identity,
    week_number int4,
    work_shift  varchar(255) not null,
    doctor_id   int8,
    primary key (id),
    constraint fk_doctor_schedule_user_entities
        foreign key (doctor_id)
            references user_entities,
    constraint doctor_id_week_number_unique
        unique (doctor_id, week_number)
);